// Mocks generated by Mockito 5.4.6 from annotations
// in cred_assignment_by_shubham_puhal/test/presentation/widgets/swipable_vertical_carousel/swipable_vertical_carousel_builder_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i4;

import 'package:cred_assignment_by_shubham_puhal/core/controllers/swipable_carousel_controller.dart'
    as _i2;
import 'package:cred_assignment_by_shubham_puhal/provider/controller_provider.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSwipableCarouselController_0 extends _i1.SmartFake
    implements _i2.SwipableCarouselController {
  _FakeSwipableCarouselController_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ControllerProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockControllerProvider extends _i1.Mock
    implements _i3.ControllerProvider {
  MockControllerProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SwipableCarouselController get carouselController =>
      (super.noSuchMethod(
            Invocation.getter(#carouselController),
            returnValue: _FakeSwipableCarouselController_0(
              this,
              Invocation.getter(#carouselController),
            ),
          )
          as _i2.SwipableCarouselController);

  @override
  bool get swipeUpEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#swipeUpEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get swipeDownEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#swipeDownEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void carouselSwipeUp() => super.noSuchMethod(
    Invocation.method(#carouselSwipeUp, []),
    returnValueForMissingStub: null,
  );

  @override
  void carouselSwipeDown() => super.noSuchMethod(
    Invocation.method(#carouselSwipeDown, []),
    returnValueForMissingStub: null,
  );

  @override
  void attach(_i4.VoidCallback? onSwipeUp, _i4.VoidCallback? onSwipeDown) =>
      super.noSuchMethod(
        Invocation.method(#attach, [onSwipeUp, onSwipeDown]),
        returnValueForMissingStub: null,
      );

  @override
  void modifySwipeUpFlag({required bool? isEnabled}) => super.noSuchMethod(
    Invocation.method(#modifySwipeUpFlag, [], {#isEnabled: isEnabled}),
    returnValueForMissingStub: null,
  );

  @override
  void modifySwipeDownFlag({required bool? isEnabled}) => super.noSuchMethod(
    Invocation.method(#modifySwipeDownFlag, [], {#isEnabled: isEnabled}),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
