// Mocks generated by Mockito 5.4.6 from annotations
// in cred_assignment_by_shubham_puhal/test/provider/bill_section_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cred_assignment_by_shubham_puhal/data/data_sources/bills_section_data_source.dart'
    as _i2;
import 'package:cred_assignment_by_shubham_puhal/data/models/section_model.dart'
    as _i3;
import 'package:cred_assignment_by_shubham_puhal/data/repository/bills_section_repository_impl.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBillsSectionDataSource_0 extends _i1.SmartFake
    implements _i2.BillsSectionDataSource {
  _FakeBillsSectionDataSource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSectionModel_1 extends _i1.SmartFake implements _i3.SectionModel {
  _FakeSectionModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BillsSectionRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockBillsSectionRepositoryImpl extends _i1.Mock
    implements _i4.BillsSectionRepositoryImpl {
  MockBillsSectionRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BillsSectionDataSource get remoteDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteDataSource),
            returnValue: _FakeBillsSectionDataSource_0(
              this,
              Invocation.getter(#remoteDataSource),
            ),
          )
          as _i2.BillsSectionDataSource);

  @override
  _i5.Future<_i3.SectionModel> getBillsSection({required String? url}) =>
      (super.noSuchMethod(
            Invocation.method(#getBillsSection, [], {#url: url}),
            returnValue: _i5.Future<_i3.SectionModel>.value(
              _FakeSectionModel_1(
                this,
                Invocation.method(#getBillsSection, [], {#url: url}),
              ),
            ),
          )
          as _i5.Future<_i3.SectionModel>);
}
