// Mocks generated by Mockito 5.4.6 from annotations
// in cred_assignment_by_shubham_puhal/test/provider/controller_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i3;

import 'package:cred_assignment_by_shubham_puhal/core/controllers/swipable_carousel_controller.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SwipableCarouselController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSwipableCarouselController extends _i1.Mock
    implements _i2.SwipableCarouselController {
  MockSwipableCarouselController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void swipeUp() => super.noSuchMethod(
    Invocation.method(#swipeUp, []),
    returnValueForMissingStub: null,
  );

  @override
  void swipeDown() => super.noSuchMethod(
    Invocation.method(#swipeDown, []),
    returnValueForMissingStub: null,
  );

  @override
  void attach(_i3.VoidCallback? onSwipeUp, _i3.VoidCallback? onSwipeDown) =>
      super.noSuchMethod(
        Invocation.method(#attach, [onSwipeUp, onSwipeDown]),
        returnValueForMissingStub: null,
      );
}
